### ISSUE TITLE
visualise point features from source dataset in map

### ISSUE THREAD

**Issue by jbalzer12** [phuef/Geoinformation-in-Society-22#61]
#72 is required for this

**Comment by jbalzer12** [comment]
Started a branch. Please join if you are interested. Currently I wait until the update branch is merged to main

**Comment by kardwen** [comment]
There is no linked branch

**Comment by kardwen** [comment]
But I can assign you the new issue instead

**Comment by kardwen** [comment]
And I strongly suggest refactoring the way the results are handled first, because at the moment the request result is sent with an event to the main component and from there to the map. It would be better to just send the request string from the menu view and fetch the result (and features) in main. I can quickly change it.

**Comment by jbalzer12** [comment]
> There is no linked branch

It's fe-visualize-source-features. We could probably merch both branches in case the code is working :) I only added a checkbox in the MenuView and for the functionality I was waiting until the Update pull request is merged to the main branch.

**Comment by jbalzer12** [comment]
And regarding your idea to had, please implement it and show us, if you think that way would be better. Important is, that the result is stored in the main component. Or it was important until we did a pre-rendering by hiding the menu. Please try!
